package GreetingLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Gender extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Gender() {
    super(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacafL, "Gender", "r:74f41bd0-f173-450e-909a-35e5a8a85bf5(GreetingLanguage.structure)/6205122835526692015");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Male_0 = new EnumerationDescriptor.MemberDescriptor("Male", "Male", 0x561d0657bf3bacb0L, "r:74f41bd0-f173-450e-909a-35e5a8a85bf5(GreetingLanguage.structure)/6205122835526692016");
  private final EnumerationDescriptor.MemberDescriptor myMember_Female_0 = new EnumerationDescriptor.MemberDescriptor("Female", "Female", 0x561d0657bf3bacb1L, "r:74f41bd0-f173-450e-909a-35e5a8a85bf5(GreetingLanguage.structure)/6205122835526692017");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacafL, 0x561d0657bf3bacb0L, 0x561d0657bf3bacb1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Male_0, myMember_Female_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Male":
        return myMember_Male_0;
      case "Female":
        return myMember_Female_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
