package GreetingLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Person = 0;
  public static final int SayGoodbyeAction = 1;
  public static final int SayHelloAction = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xa4e3811c15e04bd5L, 0x89008c50e0388469L);
    builder.put(0x561d0657bf3bacabL, Person);
    builder.put(0x561d0657bf3bacb7L, SayGoodbyeAction);
    builder.put(0x561d0657bf3bacb5L, SayHelloAction);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
