package GreetingLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptPerson = createDescriptorForPerson();
  /*package*/ final ConceptDescriptor myConceptSayGoodbyeAction = createDescriptorForSayGoodbyeAction();
  /*package*/ final ConceptDescriptor myConceptSayHelloAction = createDescriptorForSayHelloAction();
  /*package*/ final EnumerationDescriptor myEnumerationGender = new EnumerationDescriptor_Gender();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptPerson, myConceptSayGoodbyeAction, myConceptSayHelloAction);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Person:
        return myConceptPerson;
      case LanguageConceptSwitch.SayGoodbyeAction:
        return myConceptSayGoodbyeAction;
      case LanguageConceptSwitch.SayHelloAction:
        return myConceptSayHelloAction;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationGender);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForPerson() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GreetingLanguage", "Person", 0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacabL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:74f41bd0-f173-450e-909a-35e5a8a85bf5(GreetingLanguage.structure)/6205122835526692011");
    b.version(3);
    b.property("height", 0x561d0657bf3bacadL).type(PrimitiveTypeId.INTEGER).origin("6205122835526692013").done();
    b.property("familyName", 0x561d0657bf3bacaeL).type(PrimitiveTypeId.STRING).origin("6205122835526692014").done();
    b.property("gender", 0x561d0657bf3bacb3L).type(MetaIdFactory.dataTypeId(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacafL)).origin("6205122835526692019").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSayGoodbyeAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GreetingLanguage", "SayGoodbyeAction", 0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacb7L);
    b.class_(false, false, false);
    b.origin("r:74f41bd0-f173-450e-909a-35e5a8a85bf5(GreetingLanguage.structure)/6205122835526692023");
    b.version(3);
    b.associate("toPerson", 0x561d0657bf3bacb8L).target(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacabL).optional(true).origin("6205122835526692024").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSayHelloAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("GreetingLanguage", "SayHelloAction", 0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacb5L);
    b.class_(false, false, false);
    b.origin("r:74f41bd0-f173-450e-909a-35e5a8a85bf5(GreetingLanguage.structure)/6205122835526692021");
    b.version(3);
    b.associate("toPerson", 0x561d0657bf3bacb6L).target(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacabL).optional(true).origin("6205122835526692022").done();
    return b.create();
  }
}
