package GreetingLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;

public final class SayHelloAction__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacb5L, "GreetingLanguage.structure.SayHelloAction");

  public static final SMethod<String> generateMessage_id5ot1_uZfjzD = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("generateMessage").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6205122835526793449L).languageId(0x89008c50e0388469L, 0xa4e3811c15e04bd5L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(generateMessage_id5ot1_uZfjzD);

  private static void ___init___(@NotNull SNode __thisNode__) {

  }

  /*package*/ static String generateMessage_id5ot1_uZfjzD(@NotNull SNode __thisNode__) {
    String sizeString;
    String salutationString;

    if (SPropertyOperations.getEnum(SLinkOperations.getTarget(__thisNode__, LINKS.toPerson$4bUK), PROPS.gender$463n) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacafL, "GreetingLanguage.structure.Gender"), 0x561d0657bf3bacb0L, "Male")) {
      salutationString = "Mr.";
    } else {
      salutationString = "Mrs.";
    }

    if (SPropertyOperations.getInteger(SLinkOperations.getTarget(__thisNode__, LINKS.toPerson$4bUK), PROPS.height$44Dh) > 179) {
      sizeString = "big";
    } else {
      sizeString = "small";
    }

    String message = "A " + sizeString + " Welcome to " + salutationString + " " + SPropertyOperations.getString(SLinkOperations.getTarget(__thisNode__, LINKS.toPerson$4bUK), PROPS.familyName$44Si);

    return message;
  }

  /*package*/ SayHelloAction__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) generateMessage_id5ot1_uZfjzD(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink toPerson$4bUK = MetaAdapterFactory.getReferenceLink(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacb5L, 0x561d0657bf3bacb6L, "toPerson");
  }

  private static final class PROPS {
    /*package*/ static final SProperty gender$463n = MetaAdapterFactory.getProperty(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacabL, 0x561d0657bf3bacb3L, "gender");
    /*package*/ static final SProperty height$44Dh = MetaAdapterFactory.getProperty(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacabL, 0x561d0657bf3bacadL, "height");
    /*package*/ static final SProperty familyName$44Si = MetaAdapterFactory.getProperty(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacabL, 0x561d0657bf3bacaeL, "familyName");
  }
}
