package GreetingLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Person_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new SayGoodbyeAction_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new SayHelloAction_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacabL), MetaIdFactory.conceptId(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacb7L), MetaIdFactory.conceptId(0xa4e3811c15e04bd5L, 0x89008c50e0388469L, 0x561d0657bf3bacb5L)).seal();
}
